### ISSUE TITLE
C++ server端重启造成client端panic

### ISSUE THREAD

**Issue by DarknessBeforeDawn** [cloudwego/netpoll#216]
每当server端重启时，client端偶尔会出现panic，server端为C++代码，C++的grpc依赖版本为1.43.0

**报错详情**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x902720]

goroutine 89 [running]:
github.com/cloudwego/netpoll.(*linkBufferNode).Malloc(...)
       github.com/cloudwego/netpoll/nocopy_linkbuffer.go:730
github.com/cloudwego/netpoll.(*LinkBuffer).book(0xc86d608e60, 0x40000, 0x7f0b1)
        github.com/cloudwego/netpoll/nocopy_linkbuffer.go:587 +0xa0
github.com/cloudwego/netpoll.(*connection).inputs(0xcdee844e80?, {0xc000440300, 0x20, 0x20})
        github.com/cloudwego/netpoll/connection_reactor.go:77 +0x4a
github.com/cloudwego/netpoll.(*defaultPoll).handler(0xc000532280, {0xc000544000, 0x1, 0xc000544000?})
        github.com/cloudwego/netpoll/poll_default_linux.go:139 +0x10a
github.com/cloudwego/netpoll.(*defaultPoll).Wait(0xc000532280)
        github.com/cloudwego/netpoll/poll_default_linux.go:103 +0x111
created by github.com/cloudwego/netpoll.(*manager).Run
        github.com/cloudwego/netpoll/poll_manager.go:106 +0x31

```

**环境**
OS : linux
Go version : 1.18.8
netpoll version : github.com/cloudwego/netpoll v0.3.1
kitex version: github.com/cloudwego/kitex v0.4.3

**Comment by DarknessBeforeDawn** [comment]
> Is kitex grpc client panic?

没有看到kitex grpc client有报panic，panic信息里也只有netpoll，刚刚又试了一下，panic信息不同：

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8f9c68]

goroutine 117 [running]:
github.com/cloudwego/netpoll.(*LinkBuffer).bookAck(...)
        github.com/cloudwego/netpoll/nocopy_linkbuffer.go:594
github.com/cloudwego/netpoll.(*connection).inputAck(0xc0005ade00?, 0xc0005ade00?)
        github.com/cloudwego/netpoll/connection_reactor.go:84 +0x28
github.com/cloudwego/netpoll.(*defaultPoll).handler(0xc0005001e0, {0xc0001d0000, 0x1, 0xc0001d0000?})
        github.com/cloudwego/netpoll/poll_default_linux.go:142 +0x17a
github.com/cloudwego/netpoll.(*defaultPoll).Wait(0xc0005001e0)
        github.com/cloudwego/netpoll/poll_default_linux.go:103 +0x111
created by github.com/cloudwego/netpoll.(*manager).Run
        github.com/cloudwego/netpoll/poll_manager.go:106 +0x31
```

**Comment by DarknessBeforeDawn** [comment]
> @DarknessBeforeDawn hi, 你本地能复现吗？如果能复现，能否帮忙抓个panic前的 tcp 包？

本地不是很好复现，而且并不是每台机器都会出现panic，也不是每次都会出现，我想想办法

**Comment by DarknessBeforeDawn** [comment]
> @DarknessBeforeDawn hi, 你本地能复现吗？如果能复现，能否帮忙抓个panic前的 tcp 包？

@joway 本地实在不好复现，线上流量太大也不可能一直抓包，而且不确定client会不会出现panic。大概的情况我描述一下，client 端使用 grpc stream流式传输，可能传输数据比较大，会出现server重启时，stream未完全传输完的情况，我感觉和这个有关系。

**Comment by DarknessBeforeDawn** [comment]
经过我们调整服务端的退出机制，保证安全退出后，client端不再出现panic
