### ISSUE TITLE
Got a Panic

### ISSUE THREAD

**Issue by da-tai** [cloudwego/netpoll#72]
I removed sensitive information, for example, the name of functions.

Based on the log atum.go 187 is 

```
func (l *Server) handler(ctx context.Context, conn netpoll.Connection) error {
  defer conn.Writer().Flush()
  defer conn.Reader().Release()
  data, err := conn.Reader().ReadBinary(conn.Reader().Len())
  conn.Reader().Release()
  if err != nil {
	  zap.L().Error("Unable to read data", zap.ByteString("Data", data), zap.Error(err))
	  return conn.Close()
  }
  ..business logic handle data
  ...business logic loop
  return nil  <------ Line 187
}
```

```
go version
go version go1.17.3 linux/amd64
```

```
Nov  8 22:46:49 [2860435]: 2021/11/08 22:46:49.947222 logger.go:190: [Error] GOPOOL: panic in pool: gopool.DefaultPool: runtime error: invalid memory address or nil pointer dereference: goroutine 1478890 [running]:
Nov  8 22:46:49 [2860435]: runtime/debug.Stack()
Nov  8 22:46:49 [2860435]: #011/snap/go/8627/src/runtime/debug/stack.go:24 +0x65
Nov  8 22:46:49 [2860435]: github.com/bytedance/gopkg/util/gopool.(*worker).run.func1.1.1()
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/bytedance/gopkg@v0.0.0-20210705062217-74c74ebadcae/util/gopool/worker.go:61 +0x5d
Nov  8 22:46:49 [2860435]: panic({0xa34520, 0x10bc020})
Nov  8 22:46:49 [2860435]: #011/snap/go/8627/src/runtime/panic.go:1038 +0x215
Nov  8 22:46:49 2860435]: github.com/cloudwego/netpoll.(*linkBufferNode).Len(...)
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/cloudwego/netpoll@v0.0.4/nocopy_linkbuffer.go:631
Nov  8 22:46:49 [2860435]: github.com/cloudwego/netpoll.(*LinkBuffer).Release(0xdf)
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/cloudwego/netpoll@v0.0.4/nocopy_linkbuffer.go:171 +0x26
Nov  8 22:46:49 [2860435]: github.com/cloudwego/netpoll.(*connection).Release(0xc01a89c8c0)
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/cloudwego/netpoll@v0.0.4/connection_impl.go:109 +0x25
Nov  8 22:46:49 [2860435]: myfunction().handler(0xc0009806c0, {0x3, 0xc06577a820}, {0xd06648, 0xc00ef55500})

Nov  8 22:46:49 [2860435]: #011/root/goprogram/atum.go:187 +0x695
Nov  8 22:46:49 [2860435]: github.com/cloudwego/netpoll.(*connection).onRequest.func1()
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/cloudwego/netpoll@v0.0.4/connection_onevent.go:112 +0xe5
Nov  8 22:46:49 [2860435]: github.com/bytedance/gopkg/util/gopool.(*worker).run.func1.1(0xc01cf5ffd0, 0x98adae)
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/bytedance/gopkg@v0.0.0-20210705062217-74c74ebadcae/util/gopool/worker.go:68 +0x66
Nov  8 22:46:49 [2860435]: github.com/bytedance/gopkg/util/gopool.(*worker).run.func1()
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/bytedance/gopkg@v0.0.0-20210705062217-74c74ebadcae/util/gopool/worker.go:69 +0xe5
Nov  8 22:46:49 [2860435]: created by github.com/bytedance/gopkg/util/gopool.(*worker).run
Nov  8 22:46:49 [2860435]: #011/root/go/pkg/mod/github.com/bytedance/gopkg@v0.0.0-20210705062217-74c74ebadcae/util/gopool/worker.go:41 +0x5b
```

**Comment by Hchenn** [comment]
>   defer conn.Writer().Flush()
>   defer conn.Reader().Release()
>   if err != nil {
> 	  return conn.Close()
>   }

sorry for cannot execute `Release` or `Flush` after `Close` conn, there is no lock guarantee

**Comment by da-tai** [comment]
Solved!
